### ISSUE TITLE
Issue installing structureboost in 3.11.9 on Windows

### ISSUE THREAD

**Issue by ndbryant21-eng** [numeristical/structureboost#10]
Using version 3.11.9
Full error message:

Collecting structureboost
  Using cached structureboost-0.4.5.tar.gz (1.6 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.
  error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
  
  [20 lines of output]
  Traceback (most recent call last):
    File "C:\Users\nbrya\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\nbrya\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\nbrya\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\nbrya\AppData\Local\Temp\pip-build-env-239xpk0w\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\nbrya\AppData\Local\Temp\pip-build-env-239xpk0w\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
      self.run_setup()
    File "C:\Users\nbrya\AppData\Local\Temp\pip-build-env-239xpk0w\overlay\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
      super().run_setup(setup_script=setup_script)
    File "C:\Users\nbrya\AppData\Local\Temp\pip-build-env-239xpk0w\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
      exec(code, locals())
    File "<string>", line 6, in <module>
  FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by machobdc** [comment]
I'm having the same issue.

**Comment by ndbryant21-eng** [comment]
@machobdc have you tried reverting to a previous version of Python (i.e., 3.9) and installing it? I plan to do that next but have not gotten around to it yet.

**Comment by machobdc** [comment]
> @machobdc have you tried reverting to a previous version of Python (i.e., 3.9) and installing it? I plan to do that next but have not gotten around to it yet.

I haven't tried that, no.  I likely won't have a chance until later in the week.  I'll let you know how it goes.

**Comment by Sandy4321** [comment]
yes pls help how to install on windows ..
